name: card_crm
description: card_crm
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  go_router: ^7.0.1
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  http: ^0.13.5

  web_socket_channel: ^2.3.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  riverpod_lint: ^1.3.2
  custom_lint:  ^0.4.0
  freezed: ^2.3.4
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  
flutter:
  uses-material-design: true
