name: card_crm
description: card_crm
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  go_router: ^6.2.0
  hooks_riverpod: ^2.2.0
  http: ^0.13.5

  web_socket_channel: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  riverpod_lint: ^1.0.1
  custom_lint:
  
flutter:
  uses-material-design: true
